library(readr); library(dplyr); library(tidyr); library(ggplot2)
x<-read_csv("results/figure_data/item_level_with_gold.csv",show_col_types=FALSE); dir.create("figures",recursive=TRUE,showWarnings=FALSE)
o<-data.frame(condition=c("Baseline","Sovereignty-preserving"),accuracy=c(mean(x$baseline_correct),mean(x$sovereign_correct)))
p<-ggplot(o,aes(condition,accuracy))+geom_col(fill="#A33A2B",width=.6)+geom_text(aes(label=sprintf("%.1f%%",accuracy*100)),vjust=-.4)+coord_cartesian(ylim=c(0,1.08))+labs(x=NULL,y="Accuracy",title="Overall contextual lexical-semantic accuracy")+theme_minimal(base_size=13)
ggsave("figures/Figure_1_overall_accuracy.png",p,width=7,height=5,dpi=300)
f<-x%>%group_by(focus_word)%>%summarise(Baseline=mean(baseline_correct),`Sovereignty-preserving`=mean(sovereign_correct),.groups="drop")%>%pivot_longer(-focus_word,names_to="condition",values_to="accuracy")
p<-ggplot(f,aes(focus_word,accuracy,fill=condition))+geom_col(position="dodge")+coord_cartesian(ylim=c(0,1.08))+labs(x="Focus word",y="Accuracy",fill=NULL)+theme_minimal(base_size=13)
ggsave("figures/Figure_2_focus_word_accuracy.png",p,width=8,height=5,dpi=300)
t<-data.frame(transition=c("Correct→Correct","Incorrect→Correct","Correct→Incorrect","Incorrect→Incorrect"),N=c(sum(x$baseline_correct&x$sovereign_correct),sum(!x$baseline_correct&x$sovereign_correct),sum(x$baseline_correct&!x$sovereign_correct),sum(!x$baseline_correct&!x$sovereign_correct)))
p<-ggplot(t,aes(transition,N))+geom_col(fill="#2F6B4F")+geom_text(aes(label=N),vjust=-.4)+labs(x=NULL,y="Number of items")+theme_minimal(base_size=13)
ggsave("figures/Figure_3_paired_transitions.png",p,width=8,height=5,dpi=300)
